# Generated by Django 4.1.1 on 2022-09-19 15:21

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_library',
            name='release_date',
            field=models.DateField(verbose_name=datetime.datetime),
        ),
        migrations.CreateModel(
            name='songLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ManyToManyField(related_name='songlist_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
