# Generated by Django 4.1.1 on 2022-09-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0002_alter_music_library_release_date_songlikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='songLikes',
        ),
    ]
