# Generated by Django 4.1.1 on 2022-09-19 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_library', '0003_delete_songlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_library',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='music_library',
            name='likes',
            field=models.ManyToManyField(related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
